services:
  - type: web
    name: taborder-flask-app
    env: python
    buildCommand: npm run build
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000 