services:
  - type: web
    name: taborder-fullstack
    env: python
    buildCommand: "npm run build"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: PORT
        value: "10000" 